
name: Backend CI/CD

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build project
        working-directory: backend
        run: mvn clean package

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'booking-system-jar'
          path: backend/target/*.jar

      - name: build docker image
        run: docker build -t appointment-booking-backend ./backend