
name: APPOINTMENT-BOOKING CI

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: set up java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build project
        working-directory: backend
        run: mvn clean compile

      - name: run test
        working-directory: backend
        run: mvn test




