
name: Backend CI/CD

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build project
        working-directory: backend
        run: mvn clean package
  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/appointment-booking-backend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/appointment-booking-backend:1.0.${{ github.run_number }}
            ${{ secrets.DOCKERHUB_USERNAME }}/appointment-booking-backend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: false

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST}}
          username: ${{ secrets.SERVER_USER}}
          key: ${{ secrets.SERVER_SSH_KEY}}
          script: |
            cd /app
            docker compose pull
            docker compose up -d